In [5]:
import numpy as np
import pandas as pd
df=pd.read_csv(r"C:\Users\maman\Downloads\Telegram Desktop\car_dataset.csv")
df

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [6]:
df.drop("3",axis=1,inplace=True)
df

,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,168.80,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
0,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,?,audi,gas,std,two,sedan,fwd,front,99.8,177.3,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,95,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,95,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [7]:
df.drop("?",axis=1,inplace=True)
df

,alfa-romero,gas,std,two,convertible,rwd,front,88.60,168.80,64.10,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [8]:
df.columns = [ "Brand", "Fuel Type", "Aspiration", "Num of Doors", "Body Style", "Drive Wheels", "Engine Location", "Wheelbase", "Length", "Width", "Height", "Curb Weight", "Engine Type", "Num of Cylinders", "Engine Size", "Fuel System", "Bore", "Stroke", "Compression Ratio", "Horsepower","Peak RPM", "City_MPG", "Highway MPG", "Price"]
df

,Brand,Fuel Type,Aspiration,Num of Doors,Body Style,Drive Wheels,Engine Location,Wheelbase,Length,Width,...,Engine Size,Fuel System,Bore,Stroke,Compression Ratio,Horsepower,Peak RPM,City_MPG,Highway MPG,Price
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [14]:
df.isnull().sum()

Brand                0
Fuel Type            0
Aspiration           0
Num of Doors         0
Body Style           0
Drive Wheels         0
Engine Location      0
Wheelbase            0
Length               0
Width                0
Height               0
Curb Weight          0
Engine Type          0
Num of Cylinders     0
Engine Size          0
Fuel System          0
Bore                 0
Stroke               0
Compression Ratio    0
Horsepower           2
Peak RPM             2
City_MPG             0
Highway MPG          0
Price                4
dtype: int64

In [10]:
df.replace("?",np.nan,inplace=True)
df

,Brand,Fuel Type,Aspiration,Num of Doors,Body Style,Drive Wheels,Engine Location,Wheelbase,Length,Width,...,Engine Size,Fuel System,Bore,Stroke,Compression Ratio,Horsepower,Peak RPM,City_MPG,Highway MPG,Price
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [11]:
df["Num of Doors"].replace(np.nan,"two",inplace=True)
df

,Brand,Fuel Type,Aspiration,Num of Doors,Body Style,Drive Wheels,Engine Location,Wheelbase,Length,Width,...,Engine Size,Fuel System,Bore,Stroke,Compression Ratio,Horsepower,Peak RPM,City_MPG,Highway MPG,Price
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [12]:
df["Bore"] = df["Bore"].astype(float)
df["Bore"].fillna(df["Bore"].mean(),inplace=True)
df["Stroke"] = df["Stroke"].astype(float)
df["Stroke"].fillna(df["Stroke"].mean(),inplace=True)
df

,Brand,Fuel Type,Aspiration,Num of Doors,Body Style,Drive Wheels,Engine Location,Wheelbase,Length,Width,...,Engine Size,Fuel System,Bore,Stroke,Compression Ratio,Horsepower,Peak RPM,City_MPG,Highway MPG,Price
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [29]:
#print(df["Bore"].to_string())
df["Horsepower"].fillna(method="bfill",inplace=True)
df["Peak RPM"].fillna(method="bfill",inplace=True)

0

In [30]:
df.dropna(subset=["Price"],inplace=True)
df

,Brand,Fuel Type,Aspiration,Num of Doors,Body Style,Drive Wheels,Engine Location,Wheelbase,Length,Width,...,Engine Size,Fuel System,Bore,Stroke,Compression Ratio,Horsepower,Peak RPM,City_MPG,Highway MPG,Price
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [34]:
df["Horsepower"].astype(float)
df["Peak RPM"].astype(float)

0      5000.0
1      5000.0
2      5500.0
3      5500.0
4      5500.0
        ...
199    5400.0
200    5300.0
201    5500.0
202    4800.0
203    5400.0
Name: Peak RPM, Length: 200, dtype: float64

In [31]:
df.to_csv('car1.csv',index=False)

In [ ]:
pd.get_dummies(df["Fuel Type"])

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
modle=LinearRegression()

In [40]:
x=df["City_MPG"]
y=df["Price"]

In [41]:
x=x.values
x

array([21, 19, 24, 18, 19, 19, 19, 17, 23, 23, 21, 21, 20, 16, 16, 15, 47,
       38, 38, 37, 31, 24, 31, 31, 31, 24, 24, 19, 49, 31, 38, 30, 30, 30,
       30, 27, 27, 27, 27, 24, 25, 24, 24, 15, 15, 13, 30, 31, 31, 31, 31,
       17, 17, 17, 16, 26, 26, 26, 26, 36, 26, 19, 31, 22, 22, 22, 22, 16,
       16, 14, 14, 19, 37, 31, 31, 24, 23, 25, 19, 19, 19, 25, 25, 23, 23,
       31, 45, 31, 31, 31, 31, 31, 31, 31, 31, 27, 27, 17, 17, 19, 19, 17,
       19, 19, 28, 19, 25, 19, 28, 19, 25, 19, 28, 18, 37, 24, 31, 31, 31,
       24, 19, 19, 17, 17, 17, 23, 23, 21, 21, 21, 21, 19, 19, 31, 26, 26,
       32, 28, 26, 24, 24, 28, 25, 23, 23, 35, 31, 31, 31, 27, 27, 30, 30,
       34, 38, 38, 28, 28, 29, 29, 26, 26, 24, 24, 24, 24, 24, 24, 29, 30,
       27, 27, 27, 20, 19, 20, 19, 37, 27, 37, 27, 27, 37, 26, 24, 24, 19,
       33, 25, 23, 23, 24, 24, 17, 17, 23, 19, 18, 26, 19], dtype=int64)

In [42]:
x=x.reshape(-1,1)
x

array([[21],
       [19],
       [24],
       [18],
       [19],
       [19],
       [19],
       [17],
       [23],
       [23],
       [21],
       [21],
       [20],
       [16],
       [16],
       [15],
       [47],
       [38],
       [38],
       [37],
       [31],
       [24],
       [31],
       [31],
       [31],
       [24],
       [24],
       [19],
       [49],
       [31],
       [38],
       [30],
       [30],
       [30],
       [30],
       [27],
       [27],
       [27],
       [27],
       [24],
       [25],
       [24],
       [24],
       [15],
       [15],
       [13],
       [30],
       [31],
       [31],
       [31],
       [31],
       [17],
       [17],
       [17],
       [16],
       [26],
       [26],
       [26],
       [26],
       [36],
       [26],
       [19],
       [31],
       [22],
       [22],
       [22],
       [22],
       [16],
       [16],
       [14],
       [14],
       [19],
       [37],
       [31],
       [31],
       [24],
       [23],
       [25],
       [19],
       [19],
       [19],
       [25],
       [25],
       [23],
       [23],
       [31],
       [45],
       [31],
       [31],
       [31],
       [31],
       [31],
       [31],
       [31],
       [31],
       [27],
       [27],
       [17],
       [17],
       [19],
       [19],
       [17],
       [19],
       [19],
       [28],
       [19],
       [25],
       [19],
       [28],
       [19],
       [25],
       [19],
       [28],
       [18],
       [37],
       [24],
       [31],
       [31],
       [31],
       [24],
       [19],
       [19],
       [17],
       [17],
       [17],
       [23],
       [23],
       [21],
       [21],
       [21],
       [21],
       [19],
       [19],
       [31],
       [26],
       [26],
       [32],
       [28],
       [26],
       [24],
       [24],
       [28],
       [25],
       [23],
       [23],
       [35],
       [31],
       [31],
       [31],
       [27],
       [27],
       [30],
       [30],
       [34],
       [38],
       [38],
       [28],
       [28],
       [29],
       [29],
       [26],
       [26],
       [24],
       [24],
       [24],
       [24],
       [24],
       [24],
       [29],
       [30],
       [27],
       [27],
       [27],
       [20],
       [19],
       [20],
       [19],
       [37],
       [27],
       [37],
       [27],
       [27],
       [37],
       [26],
       [24],
       [24],
       [19],
       [33],
       [25],
       [23],
       [23],
       [24],
       [24],
       [17],
       [17],
       [23],
       [19],
       [18],
       [26],
       [19]], dtype=int64)

In [43]:
modle.fit(x,y)

LinearRegression()

In [46]:
modle.predict([[20]])

array([17631.49917173])

In [29]:
x=df[["Horsepower"]]
y=df["Price"]

In [22]:
from sklearn.preprocessing import MinMaxScaler

In [24]:
scaler=MinMaxScaler()

In [25]:
x=x.values
x

array([['111'],
       ['154'],
       ['102'],
       ['115'],
       ['110'],
       ['110'],
       ['110'],
       ['140'],
       ['101'],
       ['101'],
       ['121'],
       ['121'],
       ['121'],
       ['182'],
       ['182'],
       ['182'],
       ['48'],
       ['70'],
       ['70'],
       ['68'],
       ['68'],
       ['102'],
       ['68'],
       ['68'],
       ['68'],
       ['102'],
       ['88'],
       ['145'],
       ['58'],
       ['76'],
       ['60'],
       ['76'],
       ['76'],
       ['76'],
       ['76'],
       ['86'],
       ['86'],
       ['86'],
       ['86'],
       ['101'],
       ['100'],
       ['78'],
       ['90'],
       ['176'],
       ['176'],
       ['262'],
       ['68'],
       ['68'],
       ['68'],
       ['68'],
       ['68'],
       ['101'],
       ['101'],
       ['101'],
       ['135'],
       ['84'],
       ['84'],
       ['84'],
       ['84'],
       ['64'],
       ['84'],
       ['120'],
       ['72'],
       ['123'],
       ['123'],
       ['123'],
       ['123'],
       ['155'],
       ['155'],
       ['184'],
       ['184'],
       ['175'],
       ['68'],
       ['68'],
       ['68'],
       ['102'],
       ['116'],
       ['88'],
       ['145'],
       ['145'],
       ['145'],
       ['88'],
       ['88'],
       ['116'],
       ['116'],
       ['69'],
       ['55'],
       ['69'],
       ['69'],
       ['69'],
       ['69'],
       ['69'],
       ['69'],
       ['69'],
       ['69'],
       ['97'],
       ['97'],
       ['152'],
       ['152'],
       ['152'],
       ['160'],
       ['200'],
       ['160'],
       ['97'],
       ['95'],
       ['97'],
       ['95'],
       ['95'],
       ['95'],
       ['95'],
       ['95'],
       ['97'],
       ['95'],
       ['142'],
       ['68'],
       ['102'],
       ['68'],
       ['68'],
       ['68'],
       ['88'],
       ['145'],
       ['143'],
       ['207'],
       ['207'],
       ['207'],
       [<bound method Series.mode of 0      111
        1      154
        2      102
        3      115
        4      110
              ...
        199    114
        200    160
        201    134
        202    106
        203    114
        Name: Horsepower, Length: 204, dtype: object>],
       [<bound method Series.mode of 0      111
        1      154
        2      102
        3      115
        4      110
              ...
        199    114
        200    160
        201    134
        202    106
        203    114
        Name: Horsepower, Length: 204, dtype: object>],
       ['110'],
       ['110'],
       ['110'],
       ['110'],
       ['160'],
       ['160'],
       ['69'],
       ['73'],
       ['73'],
       ['82'],
       ['82'],
       ['94'],
       ['82'],
       ['111'],
       ['82'],
       ['94'],
       ['82'],
       ['111'],
       ['62'],
       ['62'],
       ['62'],
       ['62'],
       ['62'],
       ['62'],
       ['70'],
       ['70'],
       ['56'],
       ['56'],
       ['70'],
       ['70'],
       ['70'],
       ['70'],
       ['70'],
       ['112'],
       ['112'],
       ['116'],
       ['116'],
       ['116'],
       ['116'],
       ['116'],
       ['116'],
       ['92'],
       ['73'],
       ['92'],
       ['92'],
       ['92'],
       ['161'],
       ['161'],
       ['156'],
       ['156'],
       ['52'],
       ['85'],
       ['52'],
       ['85'],
       ['85'],
       ['68'],
       ['100'],
       ['90'],
       ['90'],
       ['110'],
       ['68'],
       ['88'],
       ['114'],
       ['114'],
       ['114'],
       ['114'],
       ['162'],
       ['162'],
       ['114'],
       ['160'],
       ['134'],
       ['106'],
       ['114']], dtype=object)

In [31]:
scaler.fit(x,y)

TypeError: float() argument must be a string or a number, not 'method'